name: Terraform CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Enviroments/dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.3ce64ba9-c921-40c1-b6e4-457f13e5f214 }}
          tenant-id: ${{ secrets.3c15bb8c-115d-4892-afbd-c5b9df4802d1 }}
          subscription-id: ${{ secrets.386bf8df-3557-497d-bc9b-e22e349d7257 }}
          client-secret: ${{ secrets.qFc8Q~.N2QmDdNfhiPBdLy1dS-bYZjgkILxRual4 }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
